[env]
CAIRO_PROVE_PATH = "circuit/stwo-cairo/cairo-prove/target/release/cairo-prove"
CIRCUIT_EXECUTABLE_PATH = "circuit/target/release/main.executable.json"
PROOF_PATH = "circuit/proof.json"

[tasks.cairo-prove]
alias = "cp"
description = "cairo-prove"
run = "$CAIRO_PROVE_PATH"

[tasks.fix]
alias = "f"
description = "Apply biome safe fixes and format code"
run = ["biome check --fix --config-path=biome.jsonc", "dprint fmt"]

[tasks.build-circuit-types]
dir = "circuit"
hide = true
run = "tsc --project tsconfig.build.json"
quiet = true

[tasks.build-circuit-dist]
dir = "circuit"
hide = true
run = "bun build.ts"
quiet = true

[tasks.build-circuit]
alias = "bc"
description = "Bundle circuit pkg"
dir = "circuit"
run = [
  "rm -fr dist target",
  "scarb --release build",
  "mise r build-circuit-*",
  "mkdir -p ../web/public/src/",
  "cp src/lib.cairo dist/worker.js ../web/public/",
]

[tasks.build-web]
alias = "bw"
description = "Build the web app"
dir = "web"
run = ["bun tsc -b", "bun vite build"]
quiet = true

[tasks.build]
alias = "b"
description = "Build the circuit and web app"
run = [
  "mise r build-circuit",
  "mise r build-web",
]
quiet = true

[tasks.dev]
alias = "d"
description = "Start the dev server"
dir = "web"
run = ["mise run build-circuit", "bun vite"]
quiet = true

[tasks.prove]
alias = "p"
description = "Execute the circuit with arguments - Usage: mise r p {argument}"
run = "mise r cp prove $CIRCUIT_EXECUTABLE_PATH $PROOF_PATH --arguments"

[tasks.verify]
alias = "v"
description = "Verify the proof"
run = "mise r cp verify $PROOF_PATH"

[tasks.preview]
alias = "p"
description = "Preview the app"
dir = "web"
run = "bun vite preview"
quiet = true

[tasks.test-circuit]
alias = "tc"
description = "Run circuit tests"
dir = "circuit"
run = "scarb test"

[tools]
bun = "latest"
"cargo:convco" = "latest"
dprint = "latest"
hk = "latest"
pkl = "latest"
"npm:@biomejs/biome" = "latest"
"npm:typescript" = "latest"
"asdf:scarb" = "latest"
"cargo:cairo-format" = "latest"
rust = { version = "nightly-2025-04-06", profile = "minimal" }
