name: main
on:
  # push trigger required to get coveralls monitoring of default branch
  # pull_request required to get PR coveralls comments
  push:
    branches: [main]
  pull_request:
    branches: [main]

# no need to bother caching bun deps
# https://github.com/oven-sh/setup-bun/issues/14#issuecomment-1714116221
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Noir toolchain
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash
          echo "$HOME/.nargo/bin" >> $GITHUB_PATH
          ~/.nargo/bin/noirup
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            build-circuit-types = { dir = "circuit", run = "tsc -p tsconfig.build.json" }
            build-circuit-dist = { dir = "circuit", run = "bun build.ts" }
            build-circuit = { dir = "circuit", run = ["scarb --release build", "mise r build-circuit-*", "cp  src/lib.cairo dist/worker.js ../node_modules/@cryptonerdcn/wasm-cairo/wasm-cairo_bg.wasm ../web/public/"] }
            build-web = { dir = "web", run = ["tsc -b", "bun vite build"] }
            build = { run = ["mise r build-circuit", "mise r build-web"] }
            "check-format" = { run = "dprint check --excludes mise.toml" }
            "check-lint" = { run = "biome check --config-path=biome.jsonc --no-errors-on-unmatched" }
            "check-types" = { run = ["tsc -p web/tsconfig.app.json", "tsc -p circuit/tsconfig.json"] }
            "check" = { depends = "check-*" }
            [tools]
            "asdf:scarb" = "latest"
            "cargo:cairo-format" = "latest"
            bun = "latest"
            dprint = "latest"
            "npm:@biomejs/biome" = "latest"
            "npm:typescript" = "latest"
            "rust" = { version = "nightly-2025-04-06", profile = "minimal" }
      - name: Install dependencies
        run: bun i
      - name: Build
        run: mise r build
      - name: Check
        run: mise r check
